_core:
  default_config_hash: 7Znt1G53yrQvq0AyUdiXXvVLFltNw0DF-nCR1n7eYSw
langcode: da
files:
  - social_event.metatag_settings
  - social_event.metatag_settings_open_graph
  - social_page.metatag_settings
  - social_page.metatag_settings_open_graph
  - social_profile.metatag_settings
  - social_profile.metatag_settings_open_graph
  - social_topic.metatag_settings
  - social_topic.metatag_settings_open_graph
  - social_user.metatag_settings
  - social_user.metatag_settings_open_graph
  - social_group_flexible_group.field_group_type_overview_filter
