_core:
  default_config_hash: 3mgYDspyj5REgG6ooA1izlcMzEs34kHPFUOMIXeDOco
langcode: da
entity_type_groups:
  node:
    event:
      basic: basic
      open_graph: open_graph
    page:
      basic: basic
      open_graph: open_graph
    topic:
      basic: basic
      open_graph: open_graph
  profile:
    profile:
      basic: basic
      open_graph: open_graph
  user:
    user:
      basic: basic
      open_graph: open_graph
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength: {  }
tag_scroll_max_height: ''
