_core:
  default_config_hash: C0mrL9nJdlTqxkNqOf1aINrgfODEoVHeN_g7WvKpgC4
langcode: da
signup_help: 'A welcome message with further instructions will be sent to your email address after you successfully enter your email address and a username.'
login_help: ''
verified_immediately: true
social_user_profile_landingpage: social_user.stream
