name: opensocial
type: drupal10
docroot: web
php_version: "8.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"

# Drupal-specific configuration
hooks:
  post-start:
    - exec: composer install